[package]
name = "rdc-macros"
version = "0.1.0"
edition = "2021"
authors = ["Szymon Dziwak"]
license = "MIT"

[dependencies]
syn = "1.0.107"
quote = "1.0.23"
proc-macro2 = "1.0.27"

[lib]
proc-macro = true